"""
Django settings for ArticleProject project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Get the base directory of your Django project
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Define the paths to your certificates
# CERTIFICATE_ROOT_CA_2017 = os.path.join(BASE_DIR, 'certificates', 'Microsoft RSA Root Certificate Authority 2017.pem')
# CERTIFICATE_ECC_CA_2017 = os.path.join(BASE_DIR, 'certificates', 'Microsoft ECC Root Certificate Authority 2017.pem')
# CERTIFICATE_DIGICERT_GLOBAL_ROOT_CA = os.path.join(BASE_DIR, 'certificates', 'DigiCertGlobalRootCA.pem')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv('SECRET_KEY')
SECRET_KEY = 'django-insecure-qd@6znin@+t8t6g2*dd16$w#la9x3&otlz%yv-x+(go3k6m7zo'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = os.getenv('DEBUG')
DEBUG = True

ALLOWED_HOSTS = []

# ALLOWED_HOSTS = [
#     os.getenv('ALLOWED_HOSTS')
#     ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig',
    "users.apps.UsersConfig",
    "crispy_forms",
    "crispy_bootstrap5",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ArticleProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ArticleProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Update DATABASES setting

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}




# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'dbarticle',
#         'USER': 'django_user',
#         'PASSWORD': 'admin123',
#         'HOST': '127.0.0.1',  # 73.110.238.26
#         'PORT': '3306',  # MySQL default port
#     }
# }

# DATABASES = {
#      'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': os.getenv('DATABASE_NAME'),
#         'USER': os.getenv('DATABASE_USER'),
#         'PASSWORD': os.getenv('DATABASE_PASSWORD'),
#         'HOST': os.getenv('DATABASE_HOST'),
#         'PORT': os.getenv('DATABASE_PORT'),
#         'OPTIONS': {
#              'ssl': {
#                  'ssl-ca': [
#                      ' ./Microsoft ECC Root Certificate Authority 2017.pem',
#                      ' ./Microsoft RSA Root Certificate Authority 2017.pem',
#                      ' ./DigiCertGlobalRootCA.pem',
#                  ]
#              }
#          }
#      }
# }


# settings.py

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'article_db',  # Database name
#         'username': 'django_user',  # MySQL username
#         'PASSWORD': 'Admin123',  # MySQL password
#         'hostname': 'article.mysql.database.azure.com',  # Hostname for Azure MySQL
#         'PORT': '3306',  # Default MySQL port
#         'OPTIONS': {
#             'ssl': {
#                 'ca': [
#                     CERTIFICATE_ROOT_CA_2017,  # Path to Microsoft RSA Root Certificate Authority 2017.pem
#                     CERTIFICATE_ECC_CA_2017,   # Path to Microsoft ECC Root Certificate Authority 2017.pem
#                     CERTIFICATE_DIGICERT_GLOBAL_ROOT_CA,  # Path to DigiCertGlobalRootCA.pem
#                      ]
#             }
#         }
#     }
# }







# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


STATIC_URL = 'static/'

# STATICFILES_DIRS = [BASE_DIR, 'blog/static']

# STATICFILES_DIRS = [BASE_DIR / 'blog' / 'static']

STATICFILES_DIRS = (str(BASE_DIR.joinpath('blog/static')),)


STATIC_ROOT = os.path.join(BASE_DIR / 'staticfiles')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
